### ISSUE TITLE
The block explorer always says  "Fail with error 'mv'"  error

### ISSUE THREAD

**Issue by lusharenck** [zksync-sdk/zksync2-python#10]
use python 
0x8a0f0ef395d4633369d74a374fc81e60ead6a06af30a51e3c6b02593e1555946
![UZ@{QDE`HQ$U_QA1O6WN K](https://user-images.githubusercontent.com/62750932/229709245-77e59fe2-e318-4842-a589-853b27cd7e4a.png)

```
from web3 import Web3
from eth_account import Account
from web3.middleware import geth_poa_middleware
from eth_account.signers.local import LocalAccount
from source_interaction.zksync2_python_develop.zksync2.module.module_builder import ZkSyncBuilder
from source_interaction.zksync2_python_develop.zksync2.core.types import Token
from source_interaction.zksync2_python_develop.zksync2.provider.eth_provider import EthereumProvider
from source_interaction.zksync2_python_develop.zksync2.core.types import Token, EthBlockParams


URL_TO_ETH_NETWORK = "https://endpoints.omniatech.io/v1/eth/goerli/public"
URL_TO_ETH_NETWORK = "https://goerli.infura.io/v3/"
ZKSYNC_NETWORK_URL = "https://zksync2-testnet.zksync.dev"

PRIVATE_KEY2 = bytes.fromhex("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")


def deposit(amount: float):
    zksync = ZkSyncBuilder.build(ZKSYNC_NETWORK_URL)
    eth_web3 = Web3(Web3.HTTPProvider(URL_TO_ETH_NETWORK))
    eth_web3.middleware_onion.inject(geth_poa_middleware, layer=0)
    account: LocalAccount = Account.from_key(PRIVATE_KEY2)
    eth_provider = EthereumProvider(zksync, eth_web3, account)
    wei_amount = Web3.to_wei(amount, "ether")
    eth_token = Token.create_eth()
    gas_price = int(eth_web3.eth.gas_price * 1.1)
    before_deposit = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)
    eth_provider._zksync_web3.zksync
    print(f"Before: {before_deposit}")
    addres = Web3.to_checksum_address("0x79a5b5916665735fdde66eeacb4e62628416d56c")
    l2_gas_limit = eth_provider._zksync_web3.zksync.eth_estimate_gas({
        "value":"0x38d7ea4c68000", 
        "from": addres,
        "to": addres,
        "data":"0x",
        # "eip712Meta":{"gasPerPubdata":"0x0"}
    }) # int(733664 * 2) # int(eth_provider._zksync_web3.eth.gas_price * 1.1)
    gas_per_pubdata_byte = None # 800
    gas_limit = None # 118722

    l1_tx_receipt = eth_provider.deposit(token=eth_token,
                                         amount=wei_amount,
                                         l2_gas_limit=l2_gas_limit,
                                         gas_limit=gas_limit,
                                         gas_per_pubdata_byte=gas_per_pubdata_byte,
                                         gas_price=gas_price)
    # TODO: when L2 tx

    after = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)
    print(f"After : {after}")

    print(f"Tx status: {l1_tx_receipt['status']}")


if __name__ == '__main__':
    deposit(0.001)
```
`

use javascript
0x51ee30a9b0936c76051acf07fc0b10099a002bd22105e9f279d2f60c66c55fcf
![21H%N}{2J4B~GRWFWX_FTO7](https://user-images.githubusercontent.com/62750932/229709416-b708a3eb-def4-4cf3-bcd2-8b95552cc864.png)

**The hashes they generate don't look any different, but using the python module always produces an error**

**Comment by vyastrebovvareger** [comment]
Please. use this URL `"https://rpc.ankr.com/eth_goerli"` as the URL_TO_ETH_NETWORK
And please have a try with the following example:
https://github.com/zksync-sdk/zksync2-python/blob/master/examples/01_deposit.py

**Comment by vyastrebovvareger** [comment]
I will investigate your issue as soon as possible

**Comment by lusharenck** [comment]
> 请。使用此 URL`"https://rpc.ankr.com/eth_goerli"`作为 URL_TO_ETH_NETWORK 请尝试以下示例： https: [//github.com/zksync-sdk/zksync2-python/blob/master/examples/01_deposit.py](https://github.com/zksync-sdk/zksync2-python/blob/master/examples/01_deposit.py)

I got the same error after replacing the rpc
0x8a5d3c948e182e8921b8c43fba2d9d1523a5d557b443be7257466f90d74125fd
![image](https://user-images.githubusercontent.com/62750932/229789838-83c2d961-09a3-409c-a053-082c70c0f4ab.png)

**Comment by chuwt** [comment]
I think the key of this issue is that the value sent on the deposit doesn't add the fee will be used in L2.

here the `l1_value` should be replaced with `value`.
https://github.com/zksync-sdk/zksync2-python/blob/69348c2096c91bb403e04d6f6004e7fe4051c6f2/zksync2/provider/eth_provider.py#L182-L196


Also, I think here the `gas_limit` should be `l2_gas_limit`
https://github.com/zksync-sdk/zksync2-python/blob/69348c2096c91bb403e04d6f6004e7fe4051c6f2/zksync2/provider/eth_provider.py#L179-L181

Let me know if I'm wrong😄.

**Comment by 0xth0mas** [comment]
Ran into the same issue today with deposits. Started out with error "qp" for the gas per pubdata value not being right (eth provider has this set at 50000). After I overrode that I got the "mv" error and it looks like the SDK is setting the base_cost to 0. Got around that by calculating the base cost with get_base_cost and passing it as the operator tip.

`                gas_price = web3.eth.gas_price
                operator_tip = eth_provider.get_base_cost(gas_limit=eth_provider.RECOMMENDED_DEPOSIT_L2_GAS_LIMIT, gas_per_pubdata_byte=800,gas_price=gas_price)
                l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
                                        amount=web3.to_wei(str(depositAmount), "ether"),
                                        gas_per_pubdata_byte=800,
                                        operator_tip=operator_tip)`


![image](https://user-images.githubusercontent.com/35287002/229933058-d05fd784-5811-483b-92ff-a05f6dcbb78a.png)
![image](https://user-images.githubusercontent.com/35287002/229933090-e9eaeb18-6783-4bfd-af16-18cf098bd1f8.png)

**Comment by lusharenck** [comment]
> Ran into the same issue today with deposits. Started out with error "qp" for the gas per pubdata value not being right (eth provider has this set at 50000). After I overrode that I got the "mv" error and it looks like the SDK is setting the base_cost to 0. Got around that by calculating the base cost with get_base_cost and passing it as the operator tip.
> 
> > ```
> >             gas_price = web3.eth.gas_price
> >             operator_tip = eth_provider.get_base_cost(gas_limit=eth_provider.RECOMMENDED_DEPOSIT_L2_GAS_LIMIT, gas_per_pubdata_byte=800,gas_price=gas_price)
> >             l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
> >                                     amount=web3.to_wei(str(depositAmount), "ether"),
> >                                     gas_per_pubdata_byte=800,
> >                                     operator_tip=operator_tip)
> > ```
> 
> ![image](https://user-images.githubusercontent.com/35287002/229933058-d05fd784-5811-483b-92ff-a05f6dcbb78a.png) ![image](https://user-images.githubusercontent.com/35287002/229933090-e9eaeb18-6783-4bfd-af16-18cf098bd1f8.png)

this is the right solution

**Comment by lovehhf** [comment]
> Ran into the same issue today with deposits. Started out with error "qp" for the gas per pubdata value not being right (eth provider has this set at 50000). After I overrode that I got the "mv" error and it looks like the SDK is setting the base_cost to 0. Got around that by calculating the base cost with get_base_cost and passing it as the operator tip.
> 
> > ```
> >             gas_price = web3.eth.gas_price
> >             operator_tip = eth_provider.get_base_cost(gas_limit=eth_provider.RECOMMENDED_DEPOSIT_L2_GAS_LIMIT, gas_per_pubdata_byte=800,gas_price=gas_price)
> >             l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
> >                                     amount=web3.to_wei(str(depositAmount), "ether"),
> >                                     gas_per_pubdata_byte=800,
> >                                     operator_tip=operator_tip)
> > ```
> 
> ![image](https://user-images.githubusercontent.com/35287002/229933058-d05fd784-5811-483b-92ff-a05f6dcbb78a.png) ![image](https://user-images.githubusercontent.com/35287002/229933090-e9eaeb18-6783-4bfd-af16-18cf098bd1f8.png)

I encountered the same issue today, this code can help solve it, thank you.

**Comment by lusharenck** [comment]
> Also, I think here the `gas_limit` should be `l2_gas_limit`

There is no way to solve this problem, there is a solution to the problem below
