### ISSUE TITLE
insufficient funds

### ISSUE THREAD

**Issue by Igorlende** [zksync-sdk/zksync2-python#13]
why I get error insufficient funds? I have enough funds and make a small deposit.
network goerli

C:\Users\User\PycharmProjects\zksync\venv\Scripts\python.exe C:/Users/User/PycharmProjects/zksync/main2.py
Before: 92462052031320569
0.092462052031320569
current_gas_price= 174.638303826
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\zksync\main2.py", line 140, in <module>
    deposit(0.0000000000002)
  File "C:\Users\User\PycharmProjects\zksync\main2.py", line 116, in deposit
    l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\zksync2\provider\eth_provider.py", line 132, in deposit
    return self.request_execute(
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\zksync2\provider\eth_provider.py", line 187, in request_execute
    tx_receipt = self.main_contract.request_l2_transaction(contract_l2=contract_address,
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\zksync2\manage_contracts\zksync_contract.py", line 420, in request_l2_transaction
    tx_hash = self.web3.eth.send_raw_transaction(signed_tx.rawTransaction)
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\web3\eth\eth.py", line 372, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\web3\module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\web3\manager.py", line 232, in request_blocking
    return self.formatted_response(
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\web3\manager.py", line 205, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'INTERNAL_ERROR: insufficient funds'}

Process finished with exit code 1

**Comment by andreidev1** [comment]
Can you provide a code snippet ?

**Comment by Igorlende** [comment]
`def deposit(amount: float):
    ZKSYNC_TEST_URL = "https://zksync2-testnet.zksync.dev"
    ETH_TEST_URL = "https://rpc.ankr.com/eth_goerli"
    ACCOUNT_PRIVATE_KEY = ""
    zksync = ZkSyncBuilder.build(ZKSYNC_TEST_URL)
    eth_web3 = Web3(Web3.HTTPProvider(ETH_TEST_URL))
    account: LocalAccount = Account.from_key(ACCOUNT_PRIVATE_KEY)
    eth_provider = EthereumProvider(zksync, eth_web3, account)
    wei_amount = Web3.to_wei(amount, "ether")
    eth_token = Token.create_eth()
    gas_price = eth_web3.eth.gas_price
    before_deposit = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)

    print(f"Before: {before_deposit}")
    print(eth_web3.from_wei(before_deposit, 'ether'))
    wait_gas_price(eth_web3)
    operator_tip = eth_provider.get_base_cost(gas_limit=eth_provider.RECOMMENDED_DEPOSIT_L2_GAS_LIMIT,
                                              gas_per_pubdata_byte=800, gas_price=gas_price)
    l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
                                         amount=wei_amount,
                                         operator_tip=operator_tip,
                                         gas_per_pubdata_byte=800
                                         )
    after = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)
    print(f"After : {after}")
    print(eth_web3.from_wei(after, 'ether'))
    print(f"Tx status: {l1_tx_receipt['status']}")`

**Comment by Igorlende** [comment]
`from eth_account import Account
from eth_account.signers.local import LocalAccount
from web3 import Web3

from zksync2.core.types import Token, EthBlockParams
from zksync2.module.module_builder import ZkSyncBuilder
from zksync2.provider.eth_provider import EthereumProvider


def deposit(amount: float):
    ACCOUNT_PRIVATE_KEY = ""
    ZKSYNC_TEST_URL = "https://zksync2-testnet.zksync.dev"
    ETH_TEST_URL = "https://rpc.ankr.com/eth_goerli"
    zksync = ZkSyncBuilder.build(ZKSYNC_TEST_URL)
    eth_web3 = Web3(Web3.HTTPProvider(ETH_TEST_URL))
    account: LocalAccount = Account.from_key(ACCOUNT_PRIVATE_KEY)
    eth_provider = EthereumProvider(zksync, eth_web3, account)
    wei_amount = Web3.to_wei(amount, "ether")
    eth_token = Token.create_eth()
    gas_price = eth_web3.eth.gas_price
    before_deposit = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)

    print(f"Before: {before_deposit}")
    print(eth_web3.from_wei(before_deposit, 'ether'))
    operator_tip = eth_provider.get_base_cost(gas_limit=eth_provider.RECOMMENDED_DEPOSIT_L2_GAS_LIMIT,
                                              gas_per_pubdata_byte=800, gas_price=gas_price)
    l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
                                         amount=wei_amount,
                                         operator_tip=operator_tip,
                                         gas_per_pubdata_byte=800
                                         )
    after = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)
    print(f"After : {after}")
    print(eth_web3.from_wei(after, 'ether'))
    print(f"Tx status: {l1_tx_receipt['status']}")


if __name__ == "__main__":
    deposit(0.0000000000002)
`

**Comment by Igorlende** [comment]
from eth_account import Account
from eth_account.signers.local import LocalAccount
from web3 import Web3

from zksync2.core.types import Token, EthBlockParams
from zksync2.module.module_builder import ZkSyncBuilder
from zksync2.provider.eth_provider import EthereumProvider


def deposit(amount: float):
    ACCOUNT_PRIVATE_KEY = ""
    ZKSYNC_TEST_URL = "https://zksync2-testnet.zksync.dev"
    ETH_TEST_URL = "https://rpc.ankr.com/eth_goerli"
    zksync = ZkSyncBuilder.build(ZKSYNC_TEST_URL)
    eth_web3 = Web3(Web3.HTTPProvider(ETH_TEST_URL))
    account: LocalAccount = Account.from_key(ACCOUNT_PRIVATE_KEY)
    eth_provider = EthereumProvider(zksync, eth_web3, account)
    wei_amount = Web3.to_wei(amount, "ether")
    eth_token = Token.create_eth()
    gas_price = eth_web3.eth.gas_price
    before_deposit = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)

    print(f"Before: {before_deposit}")
    print(eth_web3.from_wei(before_deposit, 'ether'))
    operator_tip = eth_provider.get_base_cost(gas_limit=eth_provider.RECOMMENDED_DEPOSIT_L2_GAS_LIMIT,
                                              gas_per_pubdata_byte=800, gas_price=gas_price)
    l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
                                         amount=wei_amount,
                                         operator_tip=operator_tip,
                                         gas_per_pubdata_byte=800
                                         )
    after = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)
    print(f"After : {after}")
    print(eth_web3.from_wei(after, 'ether'))
    print(f"Tx status: {l1_tx_receipt['status']}")


if __name__ == "__main__":
    deposit(0.0000000000002)

**Comment by Igorlende** [comment]
def deposit(amount: float):
    ACCOUNT_PRIVATE_KEY = ""
    ZKSYNC_TEST_URL = "https://zksync2-testnet.zksync.dev"
    ETH_TEST_URL = "https://rpc.ankr.com/eth_goerli"
    zksync = ZkSyncBuilder.build(ZKSYNC_TEST_URL)
    eth_web3 = Web3(Web3.HTTPProvider(ETH_TEST_URL))
    account: LocalAccount = Account.from_key(ACCOUNT_PRIVATE_KEY)
    eth_provider = EthereumProvider(zksync, eth_web3, account)
    wei_amount = Web3.to_wei(amount, "ether")
    eth_token = Token.create_eth()
    gas_price = eth_web3.eth.gas_price
    before_deposit = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)
    print(f"Before: {before_deposit}")
    print(eth_web3.from_wei(before_deposit, 'ether'))
    operator_tip = eth_provider.get_base_cost(gas_limit=eth_provider.RECOMMENDED_DEPOSIT_L2_GAS_LIMIT,
                                              gas_per_pubdata_byte=800, gas_price=gas_price)
    l1_tx_receipt = eth_provider.deposit(token=Token.create_eth(),
                                         amount=wei_amount,
                                         operator_tip=operator_tip,
                                         gas_per_pubdata_byte=800
                                         )
    after = eth_provider.get_l1_balance(eth_token, EthBlockParams.LATEST)
    print(f"After : {after}")
    print(eth_web3.from_wei(after, 'ether'))
    print(f"Tx status: {l1_tx_receipt['status']}")

**Comment by danijelTxFusion** [comment]
This error happens when the 'goerli' network gets overloaded with transactions. The transaction fee becomes too high, even exceeds the wallet balance. As a result, the transaction cannot be broadcasted to the network. Try sending your transaction when the network is not heavily loaded.
