### ISSUE TITLE
Issues when interacting with a local node

### ISSUE THREAD

**Issue by andreidev1** [zksync-sdk/zksync2-python#15]
Hi

I am trying to set up a test environment for the example python modules that are available in this repository. 
Whenever I fork the zksync testnet to my local enivronment through anvil and try to run one of the example modules I always get all kind of errors but if I try to run one of the modules with a remote testnet provider everything is fine.
Is this SDK compatible with only remote testnet node ?

For example by running this snippet code with a local provider :
```py
PROVIDER  =  "http://127.0.0.1:8545"
zk = ZkSyncBuilder.build(PROVIDER)
PRIVATE_KEY = bytes.fromhex(key)
ACCOUNT: LocalAccount = Account.from_key(PRIVATE_KEY)
nonce = w3.zksync.get_transaction_count(ACCOUNT.address, ZkBlockParams.COMMITTED.value)
print(nonce)
```
I get this error : 
```
Traceback (most recent call last):
  File "/home/andy/Desktop/medium/zk/zk/try.py", line 54, in <module>
    nonce = w3.zksync.get_transaction_count(ACCOUNT.address, ZkBlockParams.COMMITTED.value)
  File "/home/andy/Desktop/medium/zk/.venv/lib/python3.10/site-packages/web3/eth/eth.py", line 450, in get_transaction_count
    return self._get_transaction_count(account, block_identifier)
  File "/home/andy/Desktop/medium/zk/.venv/lib/python3.10/site-packages/web3/module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "/home/andy/Desktop/medium/zk/.venv/lib/python3.10/site-packages/web3/manager.py", line 232, in request_blocking
    return self.formatted_response(
  File "/home/andy/Desktop/medium/zk/.venv/lib/python3.10/site-packages/web3/manager.py", line 205, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'invalid digit found in string'}
```
But if I replace a local provider with a remote provider like `"https://zksync2-testnet.zksync.dev"` I don't get any errors.

Any suggestions ? I fork the zksync testnet through `anvil --fork-url https://zksync2-testnet.zksync.dev`

**Comment by danijelTxFusion** [comment]
There is [local-setup ](https://github.com/matter-labs/local-setup)repository which provides local environment with bunch of rich wallets. You can use on of those local wallets to interact with local network and test things out.
