### ISSUE TITLE
Failed to run test_deposit in test_zksync_web3.py

### ISSUE THREAD

**Issue by pandaforme** [zksync-sdk/zksync2-python#4]
When I try to run test case `test_deposit` in test_zksync_web3.py, it throws
```
  File "/usr/local/lib/python3.9/site-packages/zksync2/module/zksync_module.py", line 105, in to_bridge_address
    return BridgeAddresses(l1_eth_default_bridge=HexStr(to_checksum_address(t["l1EthDefaultBridge"])),
KeyError: 'l1EthDefaultBridge'
```

It looks like there is no `l1EthDefaultBridge` in a dict. Is it a bug or my setting is wrong?

**Comment by ee07b505** [comment]
The RPC node can not give the  l1EthDefaultBridge  infomation.

**Comment by pandaforme** [comment]
> The RPC node can not give the l1EthDefaultBridge infomation.

Got it. Do we need to fix the snippet of codes? Or RPC node must return `l1EthDefaultBridge` information?
```
def to_bridge_address(t: dict) -> BridgeAddresses:
    return BridgeAddresses(l1_eth_default_bridge=HexStr(to_checksum_address(t["l1EthDefaultBridge"])),
                           l2_eth_default_bridge=HexStr(to_checksum_address(t["l2EthDefaultBridge"])),
                           l1_erc20_default_bridge=HexStr(to_checksum_address(t["l1Erc20DefaultBridge"])),
                           l2_erc20_default_bridge=HexStr(to_checksum_address(t["l2Erc20DefaultBridge"])))
```

**Comment by vyastrebovvareger** [comment]
Hello guys.  There is coming soon the new release with most fixes relate to the latest changes of the ZkSync node side.
the most up to date is the develop branch
