### ISSUE TITLE
eth_estimate_gas error in testnet

### ISSUE THREAD

**Issue by SteveMBao** [zksync-sdk/zksync2-python#42]
![image](https://github.com/zksync-sdk/zksync2-python/assets/17777077/7ff20284-0945-4f53-ac54-435986817107)

I'm using zkSync Era testnet for test transfer eth use python code, but it had ContractLogicError(execution reverted) when use zksync.eth_estimate_gas method,  I'm sure the wallet has enough eth(0.00988 eth) only transfer 0.0001 eth to other wallet,
my python envoriment: python 3.10 & zksync2 0.6.0
the code is forked from [examples/02_transfer.py](https://github.com/zksync-sdk/zksync2-python/tree/master/examples/02_transfer.py)

could someone help me to fix it?

**Comment by Ivan0514Xu** [comment]
same problem

**Comment by pstemporowski** [comment]
same as well

**Comment by petarTxFusion** [comment]
This should be resolved with latest release. Also you cen checkout examples [here](https://github.com/zksync-sdk/zksync2-examples/tree/main/python)
