### ISSUE TITLE
pysha3 conflict

### ISSUE THREAD

**Issue by Act0r1** [zksync-sdk/zksync2-python#43]
When I installing, I always get this error:ERROR: Could not build wheels for pysha3, which is required to install pyproject.toml-based projects

I tried install pysha3 manually, but also get this error. Also I have created a empty pyproject.toml - nothing

**Comment by Shawnlee101** [comment]
> 当我安装时，我总是收到此错误：错误：无法为 pysha3 构建轮子，这是安装 pyproject.toml 的项目所必需的
> 
> 我尝试手动安装 pysha3，但也收到此错误。我也创建了一个空的pyproject.toml - 什么都没有


> When I installing, I always get this error:ERROR: Could not build wheels for pysha3, which is required to install pyproject.toml-based projects
> 
> I tried install pysha3 manually, but also get this error. Also I have created a empty pyproject.toml - nothing

did u sovle it? I have same problem.

**Comment by Shawnlee101** [comment]
> > 当我安装时，我总是收到此错误：错误：无法为 pysha3 构建轮子，这是安装 pyproject.toml 的项目所必需的
> > 我尝试手动安装 pysha3，但也收到此错误。我也创建了一个空的pyproject.toml - 什么都没有
> 
> > When I installing, I always get this error:ERROR: Could not build wheels for pysha3, which is required to install pyproject.toml-based projects
> > I tried install pysha3 manually, but also get this error. Also I have created a empty pyproject.toml - nothing
> 
> did u sovle it? I have same problem.

I sovled this promble by downloading the cpp-build-tools [](https://visualstudio.microsoft.com/visual-cpp-build-tools/), download it, restart pc, it works.

**Comment by ryu666zaki** [comment]
Same problem on Apple Silicon

**Comment by fala13** [comment]
creating an environment with python 3.9 worked for me to get around this particular issue (but more down the road in examples code..)

**Comment by BoboTiG** [comment]
Fixed by #52.
