### ISSUE TITLE
`maxPriorityFeePerGas` is 0 for `TxWithdraw` and `TxTransfer` transactions

### ISSUE THREAD

**Issue by comilao** [zksync-sdk/zksync2-python#64]
Both `TxWithdraw` and `TxTransfer` implement `tx712()` method, unlike other tx types (e.g. [TxCreateContract](https://github.com/zksync-sdk/zksync2-python/blob/master/zksync2/transaction/transaction_builders.py#L134) ) in [transaction_builders.py](https://github.com/zksync-sdk/zksync2-python/blob/master/zksync2/transaction/transaction_builders.py), `maxPriorityFeePerGas` for [TxWithdraw](https://github.com/zksync-sdk/zksync2-python/blob/master/zksync2/transaction/transaction_builders.py#L368) and [TxTransfer](https://github.com/zksync-sdk/zksync2-python/blob/master/zksync2/transaction/transaction_builders.py#L448) are default to 0.

May I ask are there any reasons for this?

Thank you very much in advance.

**Comment by Armankhan566** [comment]
Zksync scam with me I used 3 eth but not eligible for air drop my address is 

0x88686f7a5db76c4462efcc0b7cae5c4f9a3c15f0

Please help me zksync
