### ISSUE TITLE
How do I use zksync2-python to compile contract?

### ISSUE THREAD

**Issue by VietnameseRick** [zksync-sdk/zksync2-python#7]
How do I use zksync2-python to compile contract?

**Comment by vyastrebovvareger** [comment]
You have to use the hardhat plugin to compile the contract. Python SDK is the client for interaction with ZkSync node
I can provide an example soon

**Comment by vyastrebovvareger** [comment]
Here are the steps that you may compile your contracts

* create folder for example zksync_contracts
* inside it run: `yarn init`
* add to it the hardhat.config.ts file that is listed below
* create sub folder like contracts and organize contract files there
* run `yarn add --dev ts-node typescript`
* run `npm i @matterlabs/hardhat-zksync-solc`
* run `npm i @openzeppelin/contracts` if you are going to use it
* run `yarn hardhat compile`

hardhat.config.ts:

```
import '@matterlabs/hardhat-zksync-solc';

export default {
    zksolc: {
        version: '1.3.8',
        compilerSource: 'binary',
        settings: {
            isSystem: true
        }
    },
    networks: {
        hardhat: {
            zksync: true
        }
    },
    solidity: {
        version: '0.8.16'
    }
};
```

**Comment by danijelTxFusion** [comment]
There is a [guide](https://github.com/zksync-sdk/zksync2-python/blob/master/examples/README.md) how to use docker to compile solidity smart contracts.
