### ISSUE TITLE
Web3 v7 support

### ISSUE THREAD

**Issue by BoboTiG** [zksync-sdk/zksync2-python#75]
#### 📝 Description

Web3 v7 support would be great.

#### 🤔 Rationale

As of now, my projects using web3 + zksync are stuck on the web3 v6 version. As the ecosystem is moving fast, I would love to be able to migrate my projects to web3 v7. But for that, one blocker is zksync :)

#### 📋 Additional Context

Migration guide: https://web3py.readthedocs.io/en/latest/migration.html#migrating-from-v6-to-v7

**Comment by petarTxFusion** [comment]
Hello, thank you for raising this issue. We are planning to migrate to the latest `web3py` version in the near future. We have one more update scheduled for this/next week where we have improved provider typing and a couple of more things and after that one we will probably focus on migrating to the latest version

**Comment by dewindtk** [comment]
Hi! Our team is having the same problem. We'd love to hear an update on the migration process :)

**Comment by petarTxFusion** [comment]
We are expecting to release new version probably during next week.

**Comment by dewindtk** [comment]
Hi! Any updates? :)

**Comment by petarTxFusion** [comment]
Fixed with latest version
