### ISSUE TITLE
04_deploy_create.py - fails to deploy contract

### ISSUE THREAD

**Issue by tradable-kash** [zksync-sdk/zksync2-python#76]
04_deploy_create.py fails to create contract and throws an exception
ValueError: {'code': 3, 'message': 'max priority fee per gas higher than max fee per gas', 'data': '0x'}

It should deploy and get the contract address rather than gas fee issue.

**Comment by petarTxFusion** [comment]
On which network you are experiencing this issue?

**Comment by tradable-kash** [comment]
zkSync Sepolia - https://sepolia.era.zksync.dev

**Comment by alexhooketh** [comment]
+1, sepolia too

**Comment by petarTxFusion** [comment]
You can set `max_priority_fee_per_gas` it cant be hiegher than `gasPrice` and default one is hiegher on test net.
```
create_contract = TxCreateContract(
        web3=zk_web3,
        chain_id=chain_id,
        nonce=nonce,
        from_=account.address,
        gas_limit=0,  # UNKNOWN AT THIS STATE
        gas_price=gas_price,
        bytecode=storage_contract.bytecode,
        max_priority_fee_per_gas=0,
    )
