### ISSUE TITLE
web3.py dependency issues

### ISSUE THREAD

**Issue by danieloadebimpe** [zksync-sdk/zksync2-python#77]
### Error message 

`ImportError: cannot import name 'geth_poa_middleware' from 'web3.middleware' (/Users/daniel.adebimpe/testing-notebooks/zksync/.venv/lib/python3.11/site-packages/web3/middleware/__init__.py)`

#### Description

I have followed the installation instructions on the zksync website [here](https://sdk.zksync.io/python/installation). And i'm getting errors attempting to run the following sample code that is provided (which are just imports):

```
from eth_account import Account
from eth_account.signers.local import LocalAccount
from web3 import Web3

from zksync2.account.wallet import Wallet
from zksync2.module.module_builder import ZkSyncBuilder
```

To which I get import error seen above.

#### Dependencies 

python version - 3.11.9
web3 version - 7.4.0
zksync2 version - 1.2.0

#### Additional Context

I'm running this code inside a virtual env, on vscode.

Any help/support would be appreciated.

**Comment by petarTxFusion** [comment]
Current version only supports web3py v6. New release will come out with support for v7
