### ISSUE TITLE
Returning False when connecting to remote testnet node.

### ISSUE THREAD

**Issue by andreidev1** [zksync-sdk/zksync2-python#9]
Hi
From what I understand a ZkSyncBuilder instance is basically a Web3 object with an instance of zksync module.
Whenever I want to check if I am connected to the remote L2 zksync testnet node it always returns me False.
Sounds weird cause when I connect to a remote L1 ETH node using HTTPProvider object from Web3 instance it always returns me True.

```
from zksync2.module.module_builder import ZkSyncBuilder

ZKSYNC_TEST_URL = "https://zksync2-testnet.zksync.dev"
w3 = ZkSyncBuilder.build(ZKSYNC_TEST_URL)
print(w3.is_connected())
```

Shouldn't this snippet code return me True ?

**Comment by vyastrebovvareger** [comment]
`is_connected`  methods corresponds for the default provider of Web3 object.
Meanwhile ZkSync provider is added as the middleware_onion and ZkSync module is just attached to this Web3 obejct,
if you need this functionality It will be fixed in future
